// Template: Base Controller (ApiControllerBase.t4) version 1.1

using System.Web.Http;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace iedge.exp
{
    [RoutePrefix("event")]
    public partial class EventController : ApiController
    {


        /// <summary>
		/// Entity representing a event. Get event configuration.
		/// </summary>
        [HttpGet]
        [Route("")]
        public virtual IHttpActionResult GetBase()
        {
            // Do not modify this code
            return  ((IEventController)this).Get();
        }
    }
}
