// Template: Models (ApiModel.t4) version 1.1

// This code was generated by RAML Web Api 2 Scaffolder

namespace iedge.exp.Models
{
    public partial class Feedback
    {
        
    } // end class

} // end Models namespace
