// Template: Models (ApiModel.t4) version 1.1

// This code was generated by RAML Web Api 2 Scaffolder

using System.Collections.Generic;
using Newtonsoft.Json;

namespace iedge.exp.Models
{
    public partial class Settings
    {
        
		[JsonProperty("id")]
        public string Id { get; set; }
		[JsonProperty("title")]
        public string Title { get; set; }
		[JsonProperty("smilies")]
        public IList<string> Smilies { get; set; }
    } // end class

} // end Models namespace
