//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerFeedbackDBEntities : DbContext
    {
        public CustomerFeedbackDBEntities()
            : base("name=CustomerFeedbackDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeviceTbl> DeviceTbls { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventDevice> EventDevices { get; set; }
        public virtual DbSet<EventFeedback> EventFeedbacks { get; set; }
        public virtual DbSet<EventMetric> EventMetrics { get; set; }
        public virtual DbSet<HomeSetting> HomeSettings { get; set; }
        public virtual DbSet<IconGallery> IconGalleries { get; set; }
        public virtual DbSet<SmileyAction> SmileyActions { get; set; }
        public virtual DbSet<EventSmiley> EventSmileys { get; set; }
        public virtual DbSet<MetricElement> MetricElements { get; set; }
    }
}
