//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventFeedback
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> EventMetricID { get; set; }
        public Nullable<int> MetricElementtID { get; set; }
        public Nullable<int> Feedbackval { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual EventMetric EventMetric { get; set; }
        public virtual MetricElement MetricElement { get; set; }
    }
}
